# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - develop
  - feature/*

pool:
  vmImage: "windows-latest"

steps:
  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: "3.x"
  - task: DotNetCoreCLI@2
    displayName: "Restore dependencies"
    inputs:
      command: 'restore'
      projects: 'src/CompaniesHouse.Core.sln'
      feedsToUse: 'config'
      nugetConfigPath: 'src/nuget.config'
  - task: MSBuild@1
    inputs:
      solution: '**/*.sln'
      configuration: 'Release'
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\CompaniesHouse.Core.IntegrationTests.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)'
  - script: dotnet test ./src/CompaniesHouse.Core.ScenarioTests/CompaniesHouse.Core.ScenarioTests.csproj --configuration Release --no-build
  - script: dotnet pack ./src/CompaniesHouse.Core/CompaniesHouse.Core.csproj --configuration Release --no-build --output $(Build.ArtifactStagingDirectory)/nupkg -p:PackageVersion=1.0.$(Build.BuildId)
    displayName: "Make package"
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/nupkg'
      artifactName: drop
